### ISSUE TITLE
Footer not visible on all pages except index

### ISSUE THREAD

**Issue by VincentSven** [VincentSven/Project-Viscous#6]
Omdat deze niet een div page bevatten zoals nodig was voor de nieuwsberichten. of er moet een nieuwe wrapper class komen of er moet op iedere pagina een div id page.

**Comment by gijswl** [comment]
Fixed by c846e7a929b243d71cef5bbda65e878ed628dbaa

**Comment by VincentSven** [comment]
Sorry gijs
